name: CS-bot tests
run-name: ${{github.actor}} PR
on:
  pull_request:
    branches:
      - main
jobs:
  testing:
    runs-on:
      self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: tests
        run: |
          python3.10 -m pip install flake8
          flake8 . --ignore=E501
